openapi: 3.0.0
info:
  title: SDK Customer API
  description: |
    # Overview
    This API provides endpoints for managing customer profiles and related data in the loyalty system.
    
    # Authentication
    All endpoints require SDK authentication via the SDK API Key and customer ID. Include these in your request headers:
    ```
    sdk-api-key: your-api-key
    customer_id: CUSTOMER_ID
    ```
    
    # Rate Limiting
    - 100 requests per minute per API key
    - 1000 requests per hour per API key
    
    # Error Handling
    All endpoints follow a consistent error response format:
    ```json
    {
      "status": false,
      "message": "Error description",
      "error": {
        "code": "ERROR_CODE",
        "details": {}
      }
    }
    ```
  version: 1.0.0
tags:
  - name: SDK Customer
    description: SDK APIs for customer profile and transactions

paths:
  /customer/{customer_id}/profile:
    get:
      summary: Get customer profile
      description: |
        # Description
        Retrieves the profile information for the specified customer.
        
        # Features
        - Basic profile information
        - Tier information
        - Points balance
        - Referral information
        
        # Example Usage
        ```javascript
        GET /customer/CUST-001/profile
        ```
      tags:
        - SDK Customer
      security:
        - ApiKeyAuth: []
        - CustomerIdAuth: []
      parameters:
        - name: customer_id
          in: path
          required: true
          schema:
            type: string
          description: "Customer ID"
          example: "CUST-001"
      responses:
        200:
          description: "Customer profile retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Customer profile retrieved successfully"
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: "MongoDB document ID"
                        example: "507f1f77bcf86cd799439011"
                      customer_id:
                        type: string
                        description: "Unique customer identifier"
                        example: "CUST-001"
                      name:
                        type: string
                        description: "Customer's full name"
                        example: "John Doe"
                      email:
                        type: string
                        description: "Customer's email"
                        example: "john@example.com"
                      phone:
                        type: string
                        description: "Customer's phone number"
                        example: "+1234567890"
                      tier:
                        type: object
                        description: "Customer's current tier"
                        properties:
                          _id:
                            type: string
                            example: "507f1f77bcf86cd799439012"
                          name:
                            type: string
                            example: "Gold"
                          points_required:
                            type: number
                            example: 1000
                          benefits:
                            type: array
                            items:
                              type: string
                            example: ["Free shipping", "Priority support"]
                      referral_code:
                        type: string
                        description: "Customer's unique referral code"
                        example: "REF-456"
                      user_referer_count:
                        type: number
                        description: "Number of successful referrals"
                        example: 5
                      total_points:
                        type: number
                        description: "Total points balance"
                        example: 1500
                      last_active:
                        type: string
                        format: date-time
                        description: "Last active timestamp"
                        example: "2024-03-15T10:30:00Z"
                      status:
                        type: boolean
                        description: "Customer account status"
                        example: true
        401:
          description: "Unauthorized - Invalid SDK API key or customer ID"
        404:
          description: "Customer not found"
          
  /customer/{customer_id}/transactions:
    get:
      summary: Get customer transactions
      description: |
        # Description
        Retrieves the transaction history for the specified customer.
        
        # Features
        - Pagination support
        - Transaction type filtering
        - Date range filtering
        - Sorted by transaction date (newest first)
        
        # Example Usage
        ```javascript
        GET /customer/CUST-001/transactions?page=1&limit=10&type=earn&start_date=2024-01-01&end_date=2024-03-20
        ```
      tags:
        - SDK Customer
      security:
        - ApiKeyAuth: []
        - CustomerIdAuth: []
      parameters:
        - name: customer_id
          in: path
          required: true
          schema:
            type: string
          description: "Customer ID"
          example: "CUST-001"
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: "Page number for pagination"
          example: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: "Number of items per page"
          example: 10
        - name: type
          in: query
          schema:
            type: string
            enum: [earn, redeem, all]
            default: all
          description: "Filter by transaction type"
          example: "earn"
        - name: start_date
          in: query
          schema:
            type: string
            format: date
          description: "Filter by start date (YYYY-MM-DD)"
          example: "2024-01-01"
        - name: end_date
          in: query
          schema:
            type: string
            format: date
          description: "Filter by end date (YYYY-MM-DD)"
          example: "2024-03-20"
      responses:
        200:
          description: "Customer transactions retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Customer transactions retrieved successfully"
                  data:
                    type: object
                    properties:
                      transactions:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                              example: "507f1f77bcf86cd799439021"
                            transaction_type:
                              type: string
                              enum: [earn, redeem]
                              example: "earn"
                            transaction_date:
                              type: string
                              format: date-time
                              example: "2024-03-15T10:30:00Z"
                            points:
                              type: number
                              example: 100
                            description:
                              type: string
                              example: "Purchase at Store A"
                            reference_id:
                              type: string
                              example: "ORD-12345"
                            status:
                              type: string
                              enum: [completed, pending, cancelled]
                              example: "completed"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 50
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          total_pages:
                            type: integer
                            example: 5
        401:
          description: "Unauthorized - Invalid SDK API key or customer ID"
        404:
          description: "Customer not found" 