openapi: 3.0.0
info:
  title: SDK Kedmah Offers API
  description: |
    # Overview
    This API provides endpoints for managing Kedmah offers in the loyalty system. It allows customers to:
    - View available Kedmah offers
    - Get detailed offer information
    - Check offer eligibility
    - Track offer validity and terms
    
    # Authentication
    All endpoints require SDK authentication. Include your API key in the request header:
    ```
    Authorization: Bearer your-api-key
    ```
    
    # Rate Limiting
    - 100 requests per minute per API key
    - 1000 requests per hour per API key
    
    # Error Handling
    All endpoints follow a consistent error response format:
    ```json
    {
      "status": false,
      "message": "Error description",
      "error": {
        "code": "ERROR_CODE",
        "details": {}
      }
    }
    ```
  version: 1.0.0
tags:
  - name: SDK Kedmah Offers
    description: SDK APIs for Kedmah offer operations

paths:
  /kedmah-offers:
    get:
      summary: Get all Kedmah offers for the authenticated customer
      description: |
        # Description
        Retrieves all active Kedmah offers with eligibility status for the authenticated customer.
        
        # Features
        - Active offers only
        - Validity period filtering
        - Eligibility checking
        - Sorted by eligibility and expiry date
        - Includes service category and app type details
        
        # Example Usage
        ```javascript
        GET /kedmah-offers
        ```
      tags:
        - SDK Kedmah Offers
      responses:
        200:
          description: "Kedmah offers retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Kedmah offers fetched successfully"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: "507f1f77bcf86cd799439011"
                        title:
                          type: string
                          example: "Welcome Bonus"
                        description:
                          type: string
                          example: "Get 100 points on your first purchase"
                        posterImage:
                          type: string
                          example: "https://example.com/images/welcome-bonus.jpg"
                        serviceCategory:
                          type: object
                          properties:
                            name:
                              type: string
                              example: "Shopping"
                        appType:
                          type: object
                          properties:
                            name:
                              type: string
                              example: "Mobile App"
                        eventType:
                          type: object
                          properties:
                            name:
                              type: string
                              example: "First Purchase"
                        offerType:
                          type: string
                          example: "points"
                        isActive:
                          type: boolean
                          example: true
                        validityPeriod:
                          type: object
                          properties:
                            startDate:
                              type: string
                              format: date-time
                              example: "2024-01-01T00:00:00Z"
                            endDate:
                              type: string
                              format: date-time
                              example: "2024-12-31T23:59:59Z"
                        discountDetails:
                          type: object
                          properties:
                            points:
                              type: number
                              example: 100
                        redeemablePointsCount:
                          type: number
                          example: 100
                        eligibility:
                          type: object
                          properties:
                            isEligible:
                              type: boolean
                              example: true
                            reason:
                              type: string
                              example: "Eligible for this offer"
        401:
          description: "Unauthorized"

  /kedmah-offers/{id}:
    get:
      summary: Get specific Kedmah offer with eligibility check
      description: |
        # Description
        Retrieves detailed information about a specific Kedmah offer with eligibility status.
        
        # Features
        - Complete offer details
        - Eligibility checking
        - Transaction value validation
        - Payment method validation
        
        # Query Parameters
        - transaction_value: Optional transaction value for eligibility check
        - payment_method: Optional payment method for eligibility check
        
        # Example Usage
        ```javascript
        // Get offer details
        GET /kedmah-offers/507f1f77bcf86cd799439011
        
        // Get offer with eligibility check
        GET /kedmah-offers/507f1f77bcf86cd799439011?transaction_value=100&payment_method=KhedmahPay-Wallet
        ```
      tags:
        - SDK Kedmah Offers
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Unique offer identifier"
          example: "507f1f77bcf86cd799439011"
        - name: transaction_value
          in: query
          schema:
            type: number
          description: "Transaction value for eligibility check"
          example: 100
        - name: payment_method
          in: query
          schema:
            type: string
            enum: [Khedmah-site, KhedmahPay-Wallet]
          description: "Payment method for eligibility check"
          example: "KhedmahPay-Wallet"
      responses:
        200:
          description: "Kedmah offer retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Kedmah offer fetched successfully"
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "507f1f77bcf86cd799439011"
                      title:
                        type: string
                        example: "Welcome Bonus"
                      description:
                        type: string
                        example: "Get 100 points on your first purchase"
                      posterImage:
                        type: string
                        example: "https://example.com/images/welcome-bonus.jpg"
                      serviceCategory:
                        type: object
                        properties:
                          name:
                            type: string
                            example: "Shopping"
                      appType:
                        type: object
                        properties:
                          name:
                            type: string
                            example: "Mobile App"
                      eventType:
                        type: object
                        properties:
                          name:
                            type: string
                            example: "First Purchase"
                      offerType:
                        type: string
                        example: "points"
                      isActive:
                        type: boolean
                        example: true
                      validityPeriod:
                        type: object
                        properties:
                          startDate:
                            type: string
                            format: date-time
                            example: "2024-01-01T00:00:00Z"
                          endDate:
                            type: string
                            format: date-time
                            example: "2024-12-31T23:59:59Z"
                      discountDetails:
                        type: object
                        properties:
                          points:
                            type: number
                            example: 100
                      redeemablePointsCount:
                        type: number
                        example: 100
                      eligibility:
                        type: object
                        properties:
                          isEligible:
                            type: boolean
                            example: true
                          reason:
                            type: string
                            example: "Eligible for this offer"
        404:
          description: "Offer not found"
        401:
          description: "Unauthorized"

  /kedmah-offers/check-eligibility:
    post:
      summary: Check offer eligibility
      description: |
        # Description
        Checks if the authenticated customer is eligible for a specific offer.
        
        # Features
        - Comprehensive eligibility check
        - Transaction value validation
        - Payment method validation
        - Detailed eligibility response
        
        # Example Usage
        ```javascript
        POST /kedmah-offers/check-eligibility
        {
          "offer_id": "507f1f77bcf86cd799439011",
          "transaction_value": 100,
          "payment_method": "KhedmahPay-Wallet"
        }
        ```
      tags:
        - SDK Kedmah Offers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - offer_id
              properties:
                offer_id:
                  type: string
                  description: "Unique offer identifier"
                  example: "507f1f77bcf86cd799439011"
                transaction_value:
                  type: number
                  description: "Transaction value for eligibility check"
                  example: 100
                payment_method:
                  type: string
                  enum: [Khedmah-site, KhedmahPay-Wallet]
                  description: "Payment method for eligibility check"
                  example: "KhedmahPay-Wallet"
      responses:
        200:
          description: "Offer eligibility checked successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Offer eligibility checked successfully"
                  data:
                    type: object
                    properties:
                      offerId:
                        type: string
                        example: "507f1f77bcf86cd799439011"
                      isEligible:
                        type: boolean
                        example: true
                      reason:
                        type: string
                        example: "Eligible for this offer"
                      offerDetails:
                        type: object
                        properties:
                          title:
                            type: string
                            example: "Welcome Bonus"
                          description:
                            type: string
                            example: "Get 100 points on your first purchase"
                          offerType:
                            type: string
                            example: "points"
                          discountDetails:
                            type: object
                            properties:
                              points:
                                type: number
                                example: 100
                          validityPeriod:
                            type: object
                            properties:
                              startDate:
                                type: string
                                format: date-time
                                example: "2024-01-01T00:00:00Z"
                              endDate:
                                type: string
                                format: date-time
                                example: "2024-12-31T23:59:59Z"
                          termsAndConditions:
                            type: array
                            items:
                              type: string
                            example: [
                              "Valid only on first purchase",
                              "Minimum transaction value: 50"
                            ]
                          redemptionInstructions:
                            type: array
                            items:
                              type: string
                            example: [
                              "Points will be credited automatically",
                              "Valid for 30 days"
                            ]
        400:
          description: "Offer ID is required"
        404:
          description: "Offer not found"
        401:
          description: "Unauthorized" 