openapi: 3.0.0
info:
  title: SDK Support Tickets API
  description: |
    # Overview
    This API provides endpoints for managing customer support tickets in the loyalty system. It allows customers to:
    - Create new support tickets
    - View their support tickets
    - Add messages to tickets
    - Close and reopen tickets
    - Track ticket status and history
    
    # Authentication
    All endpoints require SDK authentication. Include your API key in the request header:
    ```
    Authorization: Bearer your-api-key
    ```
    
    # Rate Limiting
    - 100 requests per minute per API key
    - 1000 requests per hour per API key
    
    # Error Handling
    All endpoints follow a consistent error response format:
    ```json
    {
      "status": false,
      "message": "Error description",
      "error": {
        "code": "ERROR_CODE",
        "details": {}
      }
    }
    ```
  version: 1.0.0
tags:
  - name: SDK Support Tickets
    description: SDK APIs for customer support ticket operations

paths:
  /support-tickets:
    post:
      summary: Create a new support ticket
      description: |
        # Description
        Creates a new support ticket for the authenticated customer.
        
        # Features
        - Automatic ticket ID generation
        - Category-based ticket classification
        - Initial status set to "open"
        - Default priority set to "medium"
        
        # Validation Rules
        - Subject is required
        - Description is required
        - Category must be one of: Points, Redemption, Technical, Account, Other
        
        # Example Usage
        ```javascript
        POST /support-tickets
        {
          "subject": "Points not credited",
          "description": "I made a purchase but points were not credited to my account",
          "category": "Points"
        }
        ```
      tags:
        - SDK Support Tickets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - subject
                - description
                - category
              properties:
                subject:
                  type: string
                  description: "Brief description of the issue"
                  example: "Points not credited"
                description:
                  type: string
                  description: "Detailed description of the issue"
                  example: "I made a purchase but points were not credited to my account"
                category:
                  type: string
                  enum: [Points, Redemption, Technical, Account, Other]
                  description: "Category of the support ticket"
                  example: "Points"
      responses:
        201:
          description: "Support ticket created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Support ticket created successfully"
                  data:
                    type: object
                    properties:
                      ticket_id:
                        type: string
                        description: "Unique ticket identifier"
                        example: "TKT1234567890"
                      subject:
                        type: string
                        example: "Points not credited"
                      description:
                        type: string
                        example: "I made a purchase but points were not credited to my account"
                      category:
                        type: string
                        example: "Points"
                      status:
                        type: string
                        example: "open"
                      priority:
                        type: string
                        example: "medium"
                      createdAt:
                        type: string
                        format: date-time
                        example: "2024-03-20T10:00:00Z"
        400:
          description: "Invalid input data"
        401:
          description: "Unauthorized"

    get:
      summary: Get all support tickets for the authenticated customer
      description: |
        # Description
        Retrieves all support tickets for the authenticated customer with pagination and filtering options.
        
        # Features
        - Pagination support
        - Status filtering
        - Category filtering
        - Sorted by creation date (newest first)
        - Includes assigned admin details
        
        # Query Parameters
        - status: Filter by ticket status
        - category: Filter by ticket category
        - page: Page number (default: 1)
        - limit: Items per page (default: 10)
        
        # Example Usage
        ```javascript
        // Get all tickets
        GET /support-tickets
        
        // Get tickets with filters
        GET /support-tickets?status=open&category=Points&page=1&limit=20
        ```
      tags:
        - SDK Support Tickets
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [open, in_progress, resolved, closed, reopened]
          description: "Filter tickets by status"
          example: "open"
        - name: category
          in: query
          schema:
            type: string
            enum: [Points, Redemption, Technical, Account, Other]
          description: "Filter tickets by category"
          example: "Points"
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: "Page number for pagination"
          example: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: "Number of items per page"
          example: 10
      responses:
        200:
          description: "Support tickets retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Support tickets fetched successfully"
                  data:
                    type: object
                    properties:
                      tickets:
                        type: array
                        items:
                          type: object
                          properties:
                            ticket_id:
                              type: string
                              example: "TKT1234567890"
                            subject:
                              type: string
                              example: "Points not credited"
                            description:
                              type: string
                              example: "I made a purchase but points were not credited to my account"
                            category:
                              type: string
                              example: "Points"
                            status:
                              type: string
                              example: "open"
                            priority:
                              type: string
                              example: "medium"
                            assigned_to:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: "John Doe"
                                email:
                                  type: string
                                  example: "john@example.com"
                            createdAt:
                              type: string
                              format: date-time
                              example: "2024-03-20T10:00:00Z"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 50
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          totalPages:
                            type: integer
                            example: 5
        401:
          description: "Unauthorized"

  /support-tickets/{ticket_id}:
    get:
      summary: Get specific support ticket details
      description: |
        # Description
        Retrieves detailed information about a specific support ticket.
        
        # Features
        - Complete ticket information
        - Message history
        - Assigned admin details
        - Resolution notes
        
        # Example Usage
        ```javascript
        GET /support-tickets/TKT1234567890
        ```
      tags:
        - SDK Support Tickets
      parameters:
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
          description: "Unique ticket identifier"
          example: "TKT1234567890"
      responses:
        200:
          description: "Support ticket details retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Support ticket fetched successfully"
                  data:
                    type: object
                    properties:
                      ticket_id:
                        type: string
                        example: "TKT1234567890"
                      subject:
                        type: string
                        example: "Points not credited"
                      description:
                        type: string
                        example: "I made a purchase but points were not credited to my account"
                      category:
                        type: string
                        example: "Points"
                      status:
                        type: string
                        example: "open"
                      priority:
                        type: string
                        example: "medium"
                      assigned_to:
                        type: object
                        properties:
                          name:
                            type: string
                            example: "John Doe"
                          email:
                            type: string
                            example: "john@example.com"
                      messages:
                        type: array
                        items:
                          type: object
                          properties:
                            sender_type:
                              type: string
                              enum: [Customer, Admin]
                              example: "Customer"
                            message:
                              type: string
                              example: "I need help with my points"
                            created_at:
                              type: string
                              format: date-time
                              example: "2024-03-20T10:00:00Z"
                      resolution_notes:
                        type: string
                        example: "Points credited after verification"
                      resolved_at:
                        type: string
                        format: date-time
                        example: "2024-03-21T15:00:00Z"
                      closed_at:
                        type: string
                        format: date-time
                        example: "2024-03-21T15:00:00Z"
                      createdAt:
                        type: string
                        format: date-time
                        example: "2024-03-20T10:00:00Z"
        404:
          description: "Support ticket not found"
        401:
          description: "Unauthorized"

  /support-tickets/{ticket_id}/messages:
    post:
      summary: Add message to support ticket
      description: |
        # Description
        Adds a new message to an existing support ticket.
        
        # Features
        - Message tracking
        - Sender identification
        - Timestamp recording
        
        # Validation Rules
        - Ticket must exist
        - Ticket must not be closed
        - Message is required
        
        # Example Usage
        ```javascript
        POST /support-tickets/TKT1234567890/messages
        {
          "message": "Thank you for your response"
        }
        ```
      tags:
        - SDK Support Tickets
      parameters:
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
          description: "Unique ticket identifier"
          example: "TKT1234567890"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: "Message content"
                  example: "Thank you for your response"
      responses:
        200:
          description: "Message added successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Message added successfully"
                  data:
                    type: object
                    properties:
                      ticket_id:
                        type: string
                        example: "TKT1234567890"
                      messages:
                        type: array
                        items:
                          type: object
                          properties:
                            sender_type:
                              type: string
                              enum: [Customer, Admin]
                              example: "Customer"
                            message:
                              type: string
                              example: "Thank you for your response"
                            created_at:
                              type: string
                              format: date-time
                              example: "2024-03-20T11:00:00Z"
        400:
          description: "Cannot add message to closed ticket"
        404:
          description: "Support ticket not found"
        401:
          description: "Unauthorized"

  /support-tickets/{ticket_id}/close:
    post:
      summary: Close support ticket
      description: |
        # Description
        Closes an existing support ticket.
        
        # Features
        - Status update
        - Closure timestamp
        - Validation checks
        
        # Validation Rules
        - Ticket must exist
        - Ticket must not be already closed
        
        # Example Usage
        ```javascript
        POST /support-tickets/TKT1234567890/close
        ```
      tags:
        - SDK Support Tickets
      parameters:
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
          description: "Unique ticket identifier"
          example: "TKT1234567890"
      responses:
        200:
          description: "Support ticket closed successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Support ticket closed successfully"
                  data:
                    type: object
                    properties:
                      ticket_id:
                        type: string
                        example: "TKT1234567890"
                      status:
                        type: string
                        example: "closed"
                      closed_at:
                        type: string
                        format: date-time
                        example: "2024-03-20T12:00:00Z"
        400:
          description: "Ticket is already closed"
        404:
          description: "Support ticket not found"
        401:
          description: "Unauthorized"

  /support-tickets/{ticket_id}/reopen:
    post:
      summary: Reopen closed support ticket
      description: |
        # Description
        Reopens a previously closed support ticket.
        
        # Features
        - Status update
        - Closure timestamp removal
        - Validation checks
        
        # Validation Rules
        - Ticket must exist
        - Ticket must be closed
        
        # Example Usage
        ```javascript
        POST /support-tickets/TKT1234567890/reopen
        ```
      tags:
        - SDK Support Tickets
      parameters:
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
          description: "Unique ticket identifier"
          example: "TKT1234567890"
      responses:
        200:
          description: "Support ticket reopened successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Support ticket reopened successfully"
                  data:
                    type: object
                    properties:
                      ticket_id:
                        type: string
                        example: "TKT1234567890"
                      status:
                        type: string
                        example: "reopened"
                      closed_at:
                        type: string
                        format: date-time
                        nullable: true
                        example: null
        400:
          description: "Ticket is not closed"
        404:
          description: "Support ticket not found"
        401:
          description: "Unauthorized" 