openapi: 3.0.0
info:
  title: SDK Theme Settings API
  description: |
    # Overview
    This API provides endpoints for retrieving theme settings for the loyalty system.
    These settings are used to customize the appearance and branding of client applications.
    
    # Authentication
    All endpoints require SDK authentication via the SDK API Key. Include your API key in the request header:
    ```
    sdk-api-key: your-api-key
    ```
    
    # Rate Limiting
    - 100 requests per minute per API key
    - 1000 requests per hour per API key
    
    # Error Handling
    All endpoints follow a consistent error response format:
    ```json
    {
      "status": false,
      "message": "Error description",
      "error": {
        "code": "ERROR_CODE",
        "details": {}
      }
    }
    ```
  version: 1.0.0
tags:
  - name: SDK Theme Settings
    description: SDK APIs for retrieving theme and branding settings

paths:
  /theme-settings:
    get:
      summary: Get theme settings
      description: |
        # Description
        Retrieves the theme settings for the loyalty program, including colors, fonts, and branding elements.
        
        # Features
        - Complete theme settings
        - Brand assets and images
        - Color schemes
        - Typography settings
        
        # Example Usage
        ```javascript
        GET /theme-settings
        ```
      tags:
        - SDK Theme Settings
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: "Theme settings retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Theme settings retrieved successfully"
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "507f1f77bcf86cd799439011"
                      colors:
                        type: object
                        properties:
                          primary:
                            type: string
                            example: "#3f51b5"
                          secondary:
                            type: string
                            example: "#f50057"
                          accent:
                            type: string
                            example: "#ff4081"
                          background:
                            type: string
                            example: "#ffffff"
                          text:
                            type: object
                            properties:
                              primary:
                                type: string
                                example: "#212121"
                              secondary:
                                type: string
                                example: "#757575"
                          success:
                            type: string
                            example: "#4caf50"
                          warning:
                            type: string
                            example: "#ff9800"
                          error:
                            type: string
                            example: "#f44336"
                      typography:
                        type: object
                        properties:
                          font_family:
                            type: string
                            example: "Roboto, sans-serif"
                          heading_font:
                            type: string
                            example: "Montserrat, sans-serif"
                          base_font_size:
                            type: string
                            example: "16px"
                      logo:
                        type: object
                        properties:
                          main:
                            type: string
                            format: uri
                            example: "https://example.com/logo.png"
                          light:
                            type: string
                            format: uri
                            example: "https://example.com/logo-light.png"
                          dark:
                            type: string
                            format: uri
                            example: "https://example.com/logo-dark.png"
                          favicon:
                            type: string
                            format: uri
                            example: "https://example.com/favicon.ico"
                      app_name:
                        type: string
                        example: "Loyalty Rewards"
                      splash_screen:
                        type: object
                        properties:
                          background_color:
                            type: string
                            example: "#3f51b5"
                          logo:
                            type: string
                            format: uri
                            example: "https://example.com/splash-logo.png"
                      buttons:
                        type: object
                        properties:
                          border_radius:
                            type: string
                            example: "4px"
                          primary:
                            type: object
                            properties:
                              background:
                                type: string
                                example: "#3f51b5"
                              text:
                                type: string
                                example: "#ffffff"
                          secondary:
                            type: object
                            properties:
                              background:
                                type: string
                                example: "#f50057"
                              text:
                                type: string
                                example: "#ffffff"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2024-03-01T10:30:00Z"
        401:
          description: "Unauthorized - Invalid SDK API key"
        500:
          description: "Internal Server Error" 