openapi: 3.0.0
info:
  title: SDK Transactions API
  description: |
    # Overview
    This API provides endpoints for managing customer transactions in the loyalty system. It allows customers to:
    - View their transaction history
    - Get transaction details
    - View transaction summaries
    - Track points earned and redeemed
    
    # Authentication
    All endpoints require SDK authentication. Include your API key in the request header:
    ```
    Authorization: Bearer your-api-key
    ```
    
    # Rate Limiting
    - 100 requests per minute per API key
    - 1000 requests per hour per API key
    
    # Error Handling
    All endpoints follow a consistent error response format:
    ```json
    {
      "status": false,
      "message": "Error description",
      "error": {
        "code": "ERROR_CODE",
        "details": {}
      }
    }
    ```
  version: 1.0.0
tags:
  - name: SDK Transactions
    description: SDK APIs for customer transaction operations

paths:
  /transactions:
    get:
      summary: Get all transactions for the authenticated customer
      description: |
        # Description
        Retrieves all transactions for the authenticated customer with pagination and filtering options.
        
        # Features
        - Pagination support
        - Transaction type filtering
        - Date range filtering
        - Status filtering
        - Sorted by transaction date (newest first)
        - Includes point criteria and app type details
        
        # Query Parameters
        - page: Page number (default: 1)
        - limit: Items per page (default: 10)
        - transaction_type: Filter by transaction type
        - status: Filter by transaction status
        - start_date: Filter by start date
        - end_date: Filter by end date
        
        # Example Usage
        ```javascript
        // Get all transactions
        GET /transactions
        
        // Get transactions with filters
        GET /transactions?transaction_type=earn&status=completed&start_date=2024-01-01&end_date=2024-03-20&page=1&limit=20
        ```
      tags:
        - SDK Transactions
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: "Page number for pagination"
          example: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: "Number of items per page"
          example: 10
        - name: transaction_type
          in: query
          schema:
            type: string
            enum: [earn, redeem, expire, adjust]
          description: "Filter by transaction type"
          example: "earn"
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, completed, failed, cancelled]
          description: "Filter by transaction status"
          example: "completed"
        - name: start_date
          in: query
          schema:
            type: string
            format: date
          description: "Filter by start date (YYYY-MM-DD)"
          example: "2024-01-01"
        - name: end_date
          in: query
          schema:
            type: string
            format: date
          description: "Filter by end date (YYYY-MM-DD)"
          example: "2024-03-20"
      responses:
        200:
          description: "Transactions retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Transactions retrieved successfully"
                  data:
                    type: object
                    properties:
                      transactions:
                        type: array
                        items:
                          type: object
                          properties:
                            transaction_id:
                              type: string
                              example: "TXN1234567890"
                            transaction_type:
                              type: string
                              example: "earn"
                            points:
                              type: number
                              example: 100
                            status:
                              type: string
                              example: "completed"
                            transaction_date:
                              type: string
                              format: date-time
                              example: "2024-03-20T10:00:00Z"
                            point_criteria:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: "Purchase Points"
                                description:
                                  type: string
                                  example: "Earn points on purchase"
                                points:
                                  type: number
                                  example: 10
                            app_type:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: "Mobile App"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 50
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          total_pages:
                            type: integer
                            example: 5
                      summary:
                        type: object
                        properties:
                          earn:
                            type: object
                            properties:
                              total_points:
                                type: number
                                example: 1000
                              count:
                                type: integer
                                example: 10
                          redeem:
                            type: object
                            properties:
                              total_points:
                                type: number
                                example: 500
                              count:
                                type: integer
                                example: 5
        401:
          description: "Unauthorized"

  /transactions/{transaction_id}:
    get:
      summary: Get specific transaction details
      description: |
        # Description
        Retrieves detailed information about a specific transaction.
        
        # Features
        - Complete transaction information
        - Point criteria details
        - App type details
        
        # Example Usage
        ```javascript
        GET /transactions/TXN1234567890
        ```
      tags:
        - SDK Transactions
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
          description: "Unique transaction identifier"
          example: "TXN1234567890"
      responses:
        200:
          description: "Transaction details retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Transaction retrieved successfully"
                  data:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                        example: "TXN1234567890"
                      transaction_type:
                        type: string
                        example: "earn"
                      points:
                        type: number
                        example: 100
                      status:
                        type: string
                        example: "completed"
                      transaction_date:
                        type: string
                        format: date-time
                        example: "2024-03-20T10:00:00Z"
                      point_criteria:
                        type: object
                        properties:
                          name:
                            type: string
                            example: "Purchase Points"
                          description:
                            type: string
                            example: "Earn points on purchase"
                          points:
                            type: number
                            example: 10
                      app_type:
                        type: object
                        properties:
                          name:
                            type: string
                            example: "Mobile App"
        404:
          description: "Transaction not found"
        401:
          description: "Unauthorized"

  /transactions/summary:
    get:
      summary: Get transaction summary
      description: |
        # Description
        Retrieves a comprehensive summary of transactions for the authenticated customer.
        
        # Features
        - Summary by transaction type
        - Summary by status
        - Total points breakdown
        - Date range filtering
        
        # Query Parameters
        - start_date: Filter by start date (YYYY-MM-DD)
        - end_date: Filter by end date (YYYY-MM-DD)
        
        # Example Usage
        ```javascript
        // Get all-time summary
        GET /transactions/summary
        
        // Get summary for date range
        GET /transactions/summary?start_date=2024-01-01&end_date=2024-03-20
        ```
      tags:
        - SDK Transactions
      parameters:
        - name: start_date
          in: query
          schema:
            type: string
            format: date
          description: "Filter by start date (YYYY-MM-DD)"
          example: "2024-01-01"
        - name: end_date
          in: query
          schema:
            type: string
            format: date
          description: "Filter by end date (YYYY-MM-DD)"
          example: "2024-03-20"
      responses:
        200:
          description: "Transaction summary retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Transaction summary retrieved successfully"
                  data:
                    type: object
                    properties:
                      summary_by_type:
                        type: object
                        properties:
                          earn:
                            type: object
                            properties:
                              total_points:
                                type: number
                                example: 1000
                              count:
                                type: integer
                                example: 10
                              avg_points:
                                type: number
                                example: 100
                          redeem:
                            type: object
                            properties:
                              total_points:
                                type: number
                                example: 500
                              count:
                                type: integer
                                example: 5
                              avg_points:
                                type: number
                                example: 100
                      summary_by_status:
                        type: object
                        properties:
                          completed:
                            type: integer
                            example: 15
                          pending:
                            type: integer
                            example: 2
                          failed:
                            type: integer
                            example: 1
                      total_points:
                        type: object
                        properties:
                          total_earned:
                            type: number
                            example: 1000
                          total_redeemed:
                            type: number
                            example: 500
                          total_expired:
                            type: number
                            example: 100
                          total_adjusted:
                            type: number
                            example: 50
        401:
          description: "Unauthorized" 