name: Deploy Loyalty Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to VPN Server
    runs-on: self-hosted 

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker and deploy the backend
      - name: Use .env and deploy with Docker
        run: |
          set -e  # Fail if any command fails

          # Define the environment file path
          ENV_FILE_PATH=/home/loyalty/loyalty/.env/.env.production

          # Check if the .env file exists on the server
          if [ -f "$ENV_FILE_PATH" ]; then
            echo "✅ .env file found at $ENV_FILE_PATH"
            cp $ENV_FILE_PATH .env
          else
            echo "❌ .env file not found at $ENV_FILE_PATH"
            exit 1
          fi

          # Step 3: Build Docker image
          echo "🛠️ Building Docker image..."
          docker build -t loyalty-backend-img .

          # Step 4: Stop and remove any existing container
          echo "🛑 Stopping and removing existing container..."
          docker rm -f loyalty-backend-container || true

          # Step 5: Run the Docker container
          echo "🚀 Starting Docker container..."
          docker run -d \
            --name loyalty-backend-container \
            --restart always \
            -p 3000:3000 \
            --env-file .env \
            loyalty-backend-img

          echo "✅ Deployment complete!"
