name: Deploy Loyalty Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to VPN Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run run.sh on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Running the custom script on the server..."
            cd /path/to/your/script/directory
            ./run.sh  # Ensure the script is executable (`chmod +x run.sh`)

      - name: Use .env and deploy with Docker
        run: |
          set -e  # Fail if any command fails

          # Define the environment file path
          ENV_FILE_PATH=/home/ubuntu/loyalty/.env/.env.production

          # Check if the .env file exists on the server
          if [ -f "$ENV_FILE_PATH" ]; then
            echo "✅ .env file found at $ENV_FILE_PATH"
            cp $ENV_FILE_PATH .env
          else
            echo "❌ .env file not found at $ENV_FILE_PATH"
            exit 1
          fi

          echo "🛠️ Building Docker image..."
          docker build -t loyalty-backend-img .

          echo "🛑 Stopping and removing existing container..."
          docker rm -f loyalty-backend-container || true

          echo "🚀 Starting Docker container..."
          docker run -d \
            --name loyalty-backend-container \
            --restart always \
            -p 3000:3000 \
            --env-file .env \
            loyalty-backend-img

          echo "✅ Deployment complete!"
